services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
      - ./data:/data
      -  pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - data-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./init/clickhouse:/docker-entrypoint-initdb.d
      - ./data:/var/lib/clickhouse/user_files/data  
    networks:
      - data-network
    environment:
        CLICKHOUSE_DB: default
        CLICKHOUSE_USER: spark_user
        CLICKHOUSE_PASSWORD: spark_password
        CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  trino:
    image: trinodb/trino:latest
    container_name: lab4_trino
    volumes:
      - ./trino/etc:/etc/trino
    ports:
      - "8080:8080"
    networks:
      - data-network
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  clickhouse-data:
  
networks:
  data-network:
    driver: bridge